# -*- conf -*-
# Minimal foot config: no bg image, no transparency, tmux handles scrollback/multiplexing.

font=Ubuntu Mono:size=12

pad=0x0

[csd]
preferred=none

[colors]
alpha=1.0

# BEGIN_PALETTE_FOOT
background=0a0a0a
foreground=b2b2b2

regular0=0a0a0a
regular1=a75f5f
regular2=5f875f
regular3=a7873f
regular4=406464
regular5=875f87
regular6=5f8787
regular7=b2b2b2

bright0=5f5f5f
bright1=a75f5f
bright2=5f875f
bright3=a7873f
bright4=406464
bright5=875f87
bright6=5f8787
bright7=e4e4e4
# END_PALETTE_FOOT
